name: Demo Github Actions
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Give Permissions to mvnw
        run: chmod +x mvnw
      - name: Run All Test
        run: mvn verify
      - name: Build Project 
        run: mvn package
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker Image
        with:
          image: yassineabidar/github_actions_demo
          tags: v1
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.PASSWORD}}
          
      
